-- Clear existing data
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE orders;
TRUNCATE TABLE menu;
TRUNCATE TABLE restaurants;
SET FOREIGN_KEY_CHECKS = 1;

-- Insert restaurants
INSERT INTO restaurants (name, city, created, updated) VALUES
('Hyderabadi Spice House', 'Hyderabad', NOW(), NOW()),
('Mumbai Masala Kitchen', 'Mumbai', NOW(), NOW()),
('Delhi Dhaba Express', 'Delhi', NOW(), NOW()),
('Bangalore Biriyani Paradise', 'Bangalore', NOW(), NOW()),
('Chennai Curry Corner', 'Chennai', NOW(), NOW()),
('Kolkata Kitchen', 'Kolkata', NOW(), NOW()),
('Pune Pav Bhaji Point', 'Pune', NOW(), NOW()),
('Ahmedabad Thali House', 'Ahmedabad', NOW(), NOW()),
('Jaipur Junction', 'Jaipur', NOW(), NOW()),
('Lucknow Nawabi Cuisine', 'Lucknow', NOW(), NOW());

-- Insert menu items
INSERT INTO menu (dishname, dishprice, restaurant_id) VALUES
-- Hyderabadi Spice House (id: 1)
('Chicken Biryani', 220, 1),
('Mutton Biryani', 280, 1),
('Hyderabadi Haleem', 180, 1),
('Paneer Tikka', 160, 1),

-- Mumbai Masala Kitchen (id: 2)
('Butter Chicken', 250, 2),
('Pav Bhaji', 120, 2),
('Vada Pav', 40, 2),
('Paneer Tikka', 180, 2),

-- Delhi Dhaba Express (id: 3)
('Dal Makhani', 140, 3),
('Chicken Tikka Masala', 240, 3),
('Paneer Butter Masala', 200, 3),
('Naan', 30, 3),

-- Bangalore Biriyani Paradise (id: 4)
('Chicken Biryani', 200, 4),
('Veg Biryani', 150, 4),
('Mutton Biryani', 300, 4),
('Raita', 50, 4),

-- Chennai Curry Corner (id: 5)
('Chicken Chettinad', 230, 5),
('Fish Curry', 260, 5),
('Masala Dosa', 80, 5),
('Idli Sambar', 60, 5),

-- Kolkata Kitchen (id: 6)
('Chicken Biryani', 210, 6),
('Fish Fry', 180, 6),
('Mutton Kosha', 270, 6),
('Luchi', 40, 6),

-- Pune Pav Bhaji Point (id: 7)
('Pav Bhaji', 100, 7),
('Cheese Pav Bhaji', 140, 7),
('Misal Pav', 90, 7),
('Vada Pav', 35, 7),

-- Ahmedabad Thali House (id: 8)
('Gujarati Thali', 180, 8),
('Dhokla', 60, 8),
('Khandvi', 80, 8),
('Paneer Tikka', 170, 8),

-- Jaipur Junction (id: 9)
('Dal Baati Churma', 160, 9),
('Laal Maas', 290, 9),
('Gatte ki Sabzi', 140, 9),
('Paneer Tikka', 175, 9),

-- Lucknow Nawabi Cuisine (id: 10)
('Lucknowi Biryani', 260, 10),
('Galouti Kebab', 220, 10),
('Chicken Korma', 240, 10),
('Shahi Tukda', 120, 10);

-- Insert orders (generating order data based on historical ordercount values)
-- Hyderabadi Spice House
INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 96;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 2, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8) t2 LIMIT 75;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 3, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t2 LIMIT 45;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 4, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t2 LIMIT 30;

-- Mumbai Masala Kitchen
INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 5, 2, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 88;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 6, 2, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 92;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 7, 2, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2, (SELECT 1 UNION ALL SELECT 2) t3 LIMIT 150;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 8, 2, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 65;

-- Delhi Dhaba Express
INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 9, 3, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 78;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 10, 3, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 82;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 11, 3, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 70;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 12, 3, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2, (SELECT 1 UNION ALL SELECT 2) t3 LIMIT 120;

-- Bangalore Biriyani Paradise
INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 13, 4, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2, (SELECT 1 UNION ALL SELECT 2) t3 LIMIT 105;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 14, 4, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 68;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 15, 4, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 55;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 16, 4, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 90;

-- Chennai Curry Corner
INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 17, 5, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2 LIMIT 72;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 18, 5, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 58;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 19, 5, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2, (SELECT 1 UNION ALL SELECT 2) t3 LIMIT 110;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 20, 5, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 95;

-- Kolkata Kitchen
INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 21, 6, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 85;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 22, 6, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2 LIMIT 62;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 23, 6, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 48;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 24, 6, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 75;

-- Pune Pav Bhaji Point
INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 25, 7, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 98;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 26, 7, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 87;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 27, 7, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 78;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 28, 7, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3) t3 LIMIT 125;

-- Ahmedabad Thali House
INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 29, 8, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 92;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 30, 8, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 88;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 31, 8, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 65;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 32, 8, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 55;

-- Jaipur Junction
INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 33, 9, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 76;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 34, 9, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2 LIMIT 52;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 35, 9, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 68;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 36, 9, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 60;

-- Lucknow Nawabi Cuisine
INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 37, 10, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 89;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 38, 10, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2 LIMIT 71;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 39, 10, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2 LIMIT 64;

INSERT INTO orders (menu_id, restaurant_id, order_date) 
SELECT 40, 10, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 90) DAY) FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t1, (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2 LIMIT 45;
